export const SITE_CONFIG = {
  name: "Kalappura Houseboats & Tours",
  tagline: "Experience Kerala's Most Beautiful Backwaters",
  description:
    "Luxury Houseboats in Alleppey - Authentic Kerala Hospitality with Direct Booking Benefits. Handcrafted traditional houseboats with modern luxury on Kerala's backwaters.",
  address: {
    line1: "Mullackal Ward, Iron Bridge P.O",
    line2: "Thirumala East Gate Road",
    city: "Alleppey",
    state: "Kerala",
    pin: "688011",
    country: "India",
  },
  phone: "+91-9895053528",
  whatsapp: "+919895053528",
  email: "info@kalappurahouseboats.com",
  rating: 9.7,
  reviewCount: 275,
  locationRating: 9.8,
};

export const ROOMS = [
  {
    id: "standard-cabin",
    name: "3 Bedroom Houseboat",
    slug: "standard-cabin-on-boat",
    price: 17500,
    weekendPrice: 20000,
    originalPrice: 19800,
    description:
      "Our spacious 3 bedroom houseboat is perfect for families and groups. Choose 1, 2, or all 3 bedrooms on the same boat. Each room features premium linens, private bathroom, and stunning backwater views.",
    bedrooms: 3,
    beds: "3 Rooms • 2+1 per room (Double Bed + Futon)",
    size: "Large Boat",
    maxGuests: 9,
    images: [
      "/images/rooms/standard-cabin/1.jpg",
      "/images/rooms/standard-cabin/2.jpg",
      "/images/rooms/standard-cabin/3.jpg",
      "/images/rooms/standard-cabin/4.jpg",
      "/images/rooms/standard-cabin/5.jpg",
      "/images/rooms/standard-cabin/6.jpg",
      "/images/rooms/standard-cabin/7.jpg",
      "/images/rooms/standard-cabin/8.jpg",
      "/images/rooms/standard-cabin/9.jpg",
      "/images/rooms/standard-cabin/10.jpg",
      "/images/rooms/standard-cabin/11.jpg",
      "/images/rooms/standard-cabin/12.jpg",
      "/images/rooms/standard-cabin/13.jpg",
      "/images/rooms/standard-cabin/14.jpg",
      "/images/rooms/standard-cabin/15.jpg",
    ],
    amenities: [
      "Air Conditioning",
      "Private Bathroom",
      "Balcony",
      "Lake View",
      "River View",
      "Kitchen",
      "Mini Bar",
      "Free WiFi",
      "Soundproof",
      "Terrace",
    ],
    features: [
      "Private Kitchen",
      "Tea & Coffee Maker",
      "Refrigerator",
      "Kitchenware",
      "Dining Table",
      "Outdoor Dining",
      "Walk-in Shower",
      "Free Toiletries",
      "Wardrobe",
      "Seating Area",
      "Wake-up Service",
      "Private Entrance",
      "Hypoallergenic",
      "Hand Sanitizer",
    ],
    badge: "Most Popular",
    availability: 3,
  },
  {
    id: "double-twin-room",
    name: "2 Bedroom Houseboat",
    slug: "double-twin-room-lake-view",
    price: 16500,
    weekendPrice: 18500,
    originalPrice: 18400,
    description:
      "A beautiful 2 bedroom houseboat with lake views. Choose 1 or both bedrooms on the same boat. Features private bathrooms, kitchen, and a stunning terrace overlooking the backwaters.",
    bedrooms: 2,
    beds: "2 Rooms • 2+1 per room (Double Bed + Futon)",
    size: "Medium Boat",
    maxGuests: 6,
    images: [
      "/images/rooms/double-twin-room/1.jpg",
      "/images/rooms/double-twin-room/2.jpg",
      "/images/rooms/double-twin-room/3.jpg",
      "/images/rooms/double-twin-room/4.jpg",
      "/images/rooms/double-twin-room/5.jpg",
      "/images/rooms/double-twin-room/6.jpg",
      "/images/rooms/double-twin-room/7.jpg",
      "/images/rooms/double-twin-room/8.jpg",
      "/images/rooms/double-twin-room/9.jpg",
      "/images/rooms/double-twin-room/10.jpg",
    ],
    amenities: [
      "Air Conditioning",
      "Private Bathroom",
      "Lake View",
      "River View",
      "Terrace",
      "Kitchen",
      "Mini Bar",
      "Free WiFi",
    ],
    features: [
      "Private Kitchen",
      "Tea & Coffee Maker",
      "Refrigerator",
      "Kitchenware",
      "Dining Table",
      "Walk-in Shower",
      "Free Toiletries",
      "Wardrobe",
      "Seating Area",
      "Private Entrance",
    ],
    badge: "Best Value",
    availability: 2,
  },
  {
    id: "suite-river-view",
    name: "Single Bedroom Houseboat",
    slug: "suite-with-river-view",
    price: 17500,
    weekendPrice: 20000,
    originalPrice: 20000,
    description:
      "An intimate single bedroom houseboat ideal for couples. Enjoy complete privacy with panoramic river views, a luxury bedroom, and all modern amenities on your own private boat.",
    bedrooms: 1,
    beds: "1 Room • 2+1 (Double Bed + Futon Mattress)",
    size: "Compact Boat",
    maxGuests: 3,
    images: [
      "/images/rooms/suite-river-view/1.jpg",
      "/images/rooms/suite-river-view/2.jpg",
      "/images/rooms/suite-river-view/3.jpg",
      "/images/rooms/suite-river-view/4.jpg",
      "/images/rooms/suite-river-view/5.jpg",
      "/images/rooms/suite-river-view/6.jpg",
      "/images/rooms/suite-river-view/7.jpg",
      "/images/rooms/suite-river-view/8.jpg",
      "/images/rooms/suite-river-view/9.jpg",
      "/images/rooms/suite-river-view/10.jpg",
    ],
    amenities: [
      "Air Conditioning",
      "Private Bathroom",
      "Living Room",
      "River View",
      "Lake View",
      "Kitchen",
      "Mini Bar",
      "Free WiFi",
      "Premium Experience",
    ],
    features: [
      "Private Kitchen",
      "Espresso Machine",
      "Refrigerator",
      "Premium Kitchenware",
      "Dining Table",
      "Outdoor Dining",
      "Luxury Bath",
      "Premium Toiletries",
      "Walk-in Wardrobe",
      "Lounge Area",
      "Private Butler Service",
      "Private Entrance",
      "Premium Soundproofing",
    ],
    badge: "Premium",
    availability: 1,
  },
];

export const REVIEWS = [
  {
    id: 1,
    name: "Sarah Thompson",
    country: "United Kingdom",
    flag: "🇬🇧",
    rating: 10,
    date: "December 2024",
    title: "Absolutely magical experience!",
    text: "The houseboat was stunning - beautifully decorated with traditional Kerala touches. The food was incredible, especially the fish curry. The staff went above and beyond to make our honeymoon special.",
    avatar: "ST",
  },
  {
    id: 2,
    name: "Michael Chen",
    country: "Singapore",
    flag: "🇸🇬",
    rating: 9.8,
    date: "January 2025",
    title: "Best backwater experience in Kerala",
    text: "We've tried several houseboats in Alleppey, but Kalappura stands out. The cleanliness, food quality, and service are exceptional. Jose and team are wonderful hosts.",
    avatar: "MC",
  },
  {
    id: 3,
    name: "Priya & Rahul",
    country: "India",
    flag: "🇮🇳",
    rating: 9.5,
    date: "November 2024",
    title: "Perfect family getaway",
    text: "Took our kids for a weekend trip. The houseboat was spacious, safe, and the crew was very attentive. The sunset views from the deck were breathtaking. Will definitely come back!",
    avatar: "PR",
  },
  {
    id: 4,
    name: "Hans Mueller",
    country: "Germany",
    flag: "🇩🇪",
    rating: 9.8,
    date: "February 2025",
    title: "Luxury meets tradition",
    text: "Outstanding hospitality! The houseboat combines modern comfort with traditional Kerala architecture perfectly. Fresh seafood prepared by expert chefs, peaceful cruise through beautiful canals.",
    avatar: "HM",
  },
  {
    id: 5,
    name: "Emma & James",
    country: "Australia",
    flag: "🇦🇺",
    rating: 10,
    date: "March 2025",
    title: "Honeymoon dream come true",
    text: "From the flower decoration to the candlelight dinner on deck - everything was perfect for our honeymoon. The privacy, views, and service exceeded all expectations. Thank you Kalappura!",
    avatar: "EJ",
  },
];

export const EXPERIENCES = [
  {
    title: "Luxury Houseboats",
    description: "Traditional kettuvallam houseboats with modern luxury amenities",
    icon: "ship",
  },
  {
    title: "Authentic Kerala Cuisine",
    description: "Fresh seafood and traditional dishes prepared by expert chefs",
    icon: "utensils",
  },
  {
    title: "Village Walk",
    description: "Explore authentic Kerala village life and culture",
    icon: "footprints",
  },
  {
    title: "Bird Watching",
    description: "Spot exotic birds in their natural backwater habitat",
    icon: "bird",
  },
  {
    title: "Romantic Dinner",
    description: "Candlelight dinner on deck under the stars",
    icon: "heart",
  },
];

export const AMENITIES = [
  { name: "Free Parking", icon: "car" },
  { name: "Restaurant", icon: "utensils" },
  { name: "Breakfast Included", icon: "coffee" },
  { name: "Free WiFi", icon: "wifi" },
  { name: "Family Rooms", icon: "users" },
  { name: "Non-Smoking", icon: "ban" },
  { name: "Tea & Coffee", icon: "cup-soda" },
  { name: "Kitchen", icon: "chef-hat" },
  { name: "Lake View", icon: "mountain" },
  { name: "River View", icon: "waves" },
  { name: "Room Service", icon: "bell" },
  { name: "Accessible", icon: "accessibility" },
  { name: "Daily Housekeeping", icon: "sparkle" },
  { name: "24/7 Security", icon: "shield" },
];

export const FAQS = [
  {
    question: "What are the check-in and check-out times?",
    answer:
      "Check-in is at 12:00 PM (noon) and check-out is at 9:00 AM the next day. Early check-in or late check-out may be available upon request, subject to availability.",
  },
  {
    question: "What is the cancellation policy?",
    answer:
      "Free cancellation up to 7 days before check-in. Cancellations within 7 days will be charged 50% of the booking amount. No-shows will be charged the full amount.",
  },
  {
    question: "Are children welcome on the houseboat?",
    answer:
      "Yes! We are family-friendly and welcome children of all ages. We provide life jackets for children and can arrange special meals. Children under 5 stay free.",
  },
  {
    question: "Is parking available?",
    answer:
      "Yes, free private parking is available at our dock. We also offer airport shuttle services from Cochin International Airport (approximately 85 km away).",
  },
  {
    question: "What meals are included?",
    answer:
      "All packages include breakfast, lunch, evening tea with snacks, and dinner. We serve authentic Kerala cuisine with fresh seafood, vegetarian options, and can accommodate special dietary needs.",
  },
  {
    question: "What activities are available?",
    answer:
      "We offer sunset cruises, village walks, canoeing, fishing, bird watching, cooking classes, and more. Activities can be customized based on your interests.",
  },
  {
    question: "What payment methods do you accept?",
    answer:
      "We accept all major credit/debit cards, UPI, net banking, and cash. Pay at property option is also available for select bookings. International cards are accepted.",
  },
  {
    question: "Are pets allowed?",
    answer:
      "Unfortunately, pets are not allowed on our houseboats for safety and comfort reasons. We apologize for the inconvenience.",
  },
];

export const SPECIAL_OFFERS = [
  {
    id: 1,
    title: "Weekend Escape",
    description: "2 nights stay with complimentary sunset cruise and spa session",
    discount: "20% OFF",
    validUntil: "Limited Time",
    image: "/images/gallery/sunset-1.jpg",
  },
  {
    id: 2,
    title: "Honeymoon Package",
    description:
      "Romantic decoration, candlelight dinner, couple spa, and photography session",
    discount: "25% OFF",
    validUntil: "All Season",
    image: "/images/gallery/river-1.jpg",
  },
  {
    id: 3,
    title: "Family Package",
    description:
      "Extra bed, kids meals free, village tour, and fishing experience included",
    discount: "15% OFF",
    validUntil: "School Holidays",
    image: "/images/gallery/deck-1.jpg",
  },
  {
    id: 4,
    title: "Monsoon Special",
    description:
      "Experience the magical monsoon on backwaters with Ayurvedic treatments",
    discount: "30% OFF",
    validUntil: "Jun - Sep",
    image: "/images/gallery/drone-1.jpg",
  },
];
